DROP TABLE IF EXISTS films_genres;
DROP TABLE IF EXISTS friendships;
DROP TABLE IF EXISTS films_likes;
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS films;
DROP TABLE IF EXISTS genres;
DROP TABLE IF EXISTS ratings;